version: '3'
services:
    apache:
        build: .docker/apache
        container_name: bbmov_apache
        ports:
            - 80:80
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - ./app:/home/wwwroot/blablamovie
        depends_on:
            - php

    mysql:
        image: mysql:8
        container_name: bbmov_mysql
        ports:
            - 3306:3306
        volumes:
            - .docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blablamovie
            MYSQL_USER: blabla
            MYSQL_PASSWORD: movie

    php:
        build: .docker/php
        container_name: bbmov_php
        volumes:
            - ./app:/home/wwwroot/blablamovie
        depends_on:
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: bbmov_phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql