App\Entity\User:
    properties:
        email:
            -   NotNull: ~
            -   NotBlank: ~
            -   Email: ~
        password:
            -   NotNull: ~
            -   NotBlank: ~
App\Entity\UserProfile:
    properties:
        alias:
            -   NotNull: ~
            -   NotBlank: ~
        birthDate:
            -   DateTime:
                    format: 'Y-m-d'
            -   LessThan: 'today'
            -   NotNull: ~
            -   NotBlank: ~